[programs.localnet]
infiniti = "A4XDsSnZot6fvPCi8rUQunTXaxXXhFsrrAC4W9B9uscs"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/jett/.config/solana/id.json"

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
